# Generated by Django 4.0.4 on 2022-05-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sanctuary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Donar_name', models.CharField(max_length=30)),
                ('Animal_name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=40)),
                ('weight', models.CharField(max_length=40)),
                ('phoneno_of_donar', models.CharField(max_length=40)),
                ('email_of_donar', models.EmailField(max_length=254)),
            ],
        ),
    ]
